// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL_B8tpZuRCLroZJCWONGbVMTPEENYKrM',
    appId: '1:301535819244:web:1e613a084f2533c021bcc9',
    messagingSenderId: '301535819244',
    projectId: 'pt-idea',
    authDomain: 'pt-idea.firebaseapp.com',
    storageBucket: 'pt-idea.appspot.com',
    measurementId: 'G-Y5YXYXEGZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2CvKPuWviV2JkW4wYE6CQIURpXyRBzl8',
    appId: '1:301535819244:android:430713355f3be31b21bcc9',
    messagingSenderId: '301535819244',
    projectId: 'pt-idea',
    storageBucket: 'pt-idea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxFjgMT4FGsM7EZEI6i4u53LCq-RbPaaI',
    appId: '1:301535819244:ios:08a48e51701fe29121bcc9',
    messagingSenderId: '301535819244',
    projectId: 'pt-idea',
    storageBucket: 'pt-idea.appspot.com',
    iosBundleId: 'com.example.ideaTuitionManagmentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxFjgMT4FGsM7EZEI6i4u53LCq-RbPaaI',
    appId: '1:301535819244:ios:1db8e5704ed8509921bcc9',
    messagingSenderId: '301535819244',
    projectId: 'pt-idea',
    storageBucket: 'pt-idea.appspot.com',
    iosBundleId: 'com.example.ideaTuitionManagmentApp.RunnerTests',
  );
}
